M48
; DRILL file {KiCad (6.0.7-1)-1} date Tuesday, August 23, 2022 at 12:40:28 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-23T12:40:28-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X170.62Y-108.19
X171.89Y-184.39
X217.6Y-184.4
X218.9Y-109.5
T0
M30
